import './globals.css'
import '@repo/ui/styles.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { HeroUIProvider } from '@heroui/system'
import { Column } from '@repo/ui/components/Layout'
import { NaverMapProvider } from '@/app/NaverMapProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ko' suppressHydrationWarning={true}>
      <body className={pretendard.className}>
        <HeroUIProvider>
          <NaverMapProvider>
            <div className={'flex h-svh justify-center bg-[#FEFCF9]'}>
              <Column className={'relative w-full max-w-[450px] bg-white'}>
                {children}
              </Column>
            </div>
          </NaverMapProvider>
        </HeroUIProvider>
      </body>
    </html>
  )
}
