import '@repo/ui/styles.css'
import './globals.css'
import type { Metadata } from 'next'
import QueryProvider from './QueryClientProvider'
import localFont from 'next/font/local'
import { Column } from '@repo/ui/components/Layout/Column'

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

const pretendard = localFont({
  src: '../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='ko'>
      <body className={pretendard.className}>
        <QueryProvider>
          <div className={'flex h-svh justify-center bg-gray-50'}>
            <Column className={'relative w-[450px] max-w-[450px] bg-white'}>
              {children}
            </Column>
          </div>
        </QueryProvider>
      </body>
    </html>
  )
}
