import '@repo/ui/styles.css'
import './globals.css'
import 'keen-slider/keen-slider.min.css'
import type { Metadata } from 'next'
import QueryProvider from './QueryClientProvider'
import localFont from 'next/font/local'
import { initServerMSW } from '@/_mocks/initMSW'
import { MSWProvider } from '@/_mocks/MSWProvider'
import { Column } from '@repo/ui/components/Layout/Column'

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

const pretendard = localFont({
  src: '../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
})

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  await initServerMSW()

  return (
    <html lang='ko' suppressHydrationWarning={true}>
      <body className={pretendard.className}>
        <MSWProvider>
          <QueryProvider>
            <div className={'flex h-svh justify-center bg-gray-50'}>
              <Column className={'relative w-[450px] max-w-[450px] bg-white'}>
                {children}
              </Column>
            </div>
          </QueryProvider>
        </MSWProvider>
      </body>
    </html>
  )
}
