import '@repo/ui/styles.css'
import './globals.css'
import 'keen-slider/keen-slider.min.css'
import type { Metadata } from 'next'
import QueryProvider from './QueryClientProvider'
import localFont from 'next/font/local'
import { initServerMSW } from '@/_mocks/initMSW'
import { MSWProvider } from '@/_mocks/MSWProvider'
import { HeroUIProvider } from '@heroui/system'
import { Column } from '@repo/ui/components/Layout'
import { NaverMapProvider } from '@/NaverMapProvider'

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

const pretendard = localFont({
  src: '../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
})

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  await initServerMSW()

  return (
    <html lang='ko' suppressHydrationWarning={true}>
      <body className={pretendard.className}>
        <MSWProvider>
          <QueryProvider>
            <HeroUIProvider>
              <NaverMapProvider>
                <div className={'flex h-svh justify-center bg-[#FEFCF9]'}>
                  <Column className={'relative w-full max-w-[450px] bg-white'}>
                    {children}
                  </Column>
                </div>
              </NaverMapProvider>
            </HeroUIProvider>
          </QueryProvider>
        </MSWProvider>
      </body>
    </html>
  )
}
